# **Carga de datos**

---



In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

# Cargar los datos
disp_df = pd.read_pickle("attrition_available_17.pkl")

disp_df_target = disp_df['Attrition']

In [ ]:
# Mostrar los datos y el nombre de las columnas
display(disp_df)

hrs  absences  JobInvolvement  PerformanceRating  \
1      7.315971      13.0             2.0                4.0   
6      6.450877      17.0             3.0                4.0   
13     8.871421      14.0             2.0                3.0   
28    10.713066       6.0             2.0                3.0   
30     9.662808      11.0             2.0                3.0   
...         ...       ...             ...                ...   
4405   8.316921       6.0             3.0                3.0   
4406   5.897197       8.0             2.0                3.0   
4407   7.149526      18.0             3.0                4.0   
4408   9.187612       NaN             2.0                3.0   
4409   6.511790      17.0             4.0                3.0   

      EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance   Age  \
1                         3.0              2.0              4.0  31.0   
6                         1.0              3.0              1.0  28.0   
13                        1.0              NaN              2.0  47.0   
28                        4.0              3.0              1.0  44.0   
30                        1.0              NaN              3.0  26.0   
...                       ...              ...              ...   ...   
4405                      4.0              1.0              3.0  42.0   
4406                      4.0              NaN              3.0  29.0   
4407                      1.0              3.0              3.0   NaN   
4408                      NaN              1.0              3.0   NaN   
4409                      NaN              3.0              NaN  40.0   

     Attrition     BusinessTravel  ... NumCompaniesWorked  Over18  \
1          Yes  Travel_Frequently  ...                0.0       Y   
6          Yes      Travel_Rarely  ...                NaN       Y   
13         Yes         Non-Travel  ...                1.0     NaN   
28         Yes  Travel_Frequently  ...                3.0     NaN   
30         Yes      Travel_Rarely  ...                2.0       Y   
...        ...                ...  ...                ...     ...   
4405        No      Travel_Rarely  ...                3.0       Y   
4406        No      Travel_Rarely  ...                2.0       Y   
4407        No      Travel_Rarely  ...                0.0       Y   
4408        No      Travel_Rarely  ...                NaN       Y   
4409        No      Travel_Rarely  ...                0.0       Y   

      PercentSalaryHike StandardHours  StockOptionLevel  TotalWorkingYears  \
1                  23.0           8.0               1.0                6.0   
6                   NaN           8.0               1.0                5.0   
13                 11.0           8.0               NaN                NaN   
28                 14.0           8.0               1.0               19.0   
30                 11.0           8.0               0.0                5.0   
...                 ...           ...               ...                ...   
4405               17.0           8.0               NaN               10.0   
4406               15.0           8.0               0.0                NaN   
4407               20.0           8.0               NaN                NaN   
4408               14.0           8.0               NaN                NaN   
4409               12.0           8.0               0.0                NaN   

     TrainingTimesLastYear  YearsAtCompany YearsSinceLastPromotion  \
1                      3.0             5.0                     1.0   
6                      2.0             0.0                     0.0   
13                     4.0            10.0                     9.0   
28                     2.0             1.0                     0.0   
30                     5.0             3.0                     0.0   
...                    ...             ...                     ...   
4405                   NaN             NaN                     NaN   
4406                   2.0             3

En el dataset proporcionado se encuentran 4410 instancias y 31 atributos, de los cuales hay 23 numéricos, 2 ordinales (MaritalStatus y BusinessTravel) y 6 categóricos.

# **Análisis Exploratorio de Datos (EDA)**

---

In [ ]:
# Primero, observamos el tipo de dato de cada columna para ver si hay alguna que contiene valores nulos
disp_df.dtypes

hrs                        float64
absences                   float64
JobInvolvement             float64
PerformanceRating          float64
EnvironmentSatisfaction    float64
JobSatisfaction            float64
WorkLifeBalance            float64
Age                        float64
Attrition                   object
BusinessTravel              object
Department                  object
DistanceFromHome           float64
Education                  float64
EducationField              object
EmployeeCount              float64
EmployeeID                   int64
Gender                      object
JobLevel                     int64
JobRole                     object
MaritalStatus               object
MonthlyIncome              float64
NumCompaniesWorked         float64
Over18                      object
PercentSalaryHike          float64
StandardHours              float64
StockOptionLevel           float64
TotalWorkingYears          float64
TrainingTimesLastYear      float64
YearsAtCompany      

In [ ]:
print("% Nan Values hrs: "+ str(disp_df['hrs'].isna().sum()/44.10))
print("% Nan Values absences: "+ str(disp_df['absences'].isna().sum()/44.10))
print("% Nan Values JobInvolvement: "+ str(disp_df['JobInvolvement'].isna().sum()/44.10))
print("% Nan Values PerformanceRating: "+ str(disp_df['PerformanceRating'].isna().sum()/44.10))
print("% Nan Values EnvironmentSatisfaction: "+ str(disp_df['EnvironmentSatisfaction'].isna().sum()/44.10))
print("% Nan Values JobSatisfaction: "+ str(disp_df['JobSatisfaction'].isna().sum()/44.10))
print("% Nan Values WorkLifeBalance: "+ str(disp_df['WorkLifeBalance'].isna().sum()/44.10))
print("% Nan Values Age: "+ str(disp_df['Age'].isna().sum()/44.10))
print("% Nan Values Attrition: "+ str(disp_df['Attrition'].isna().sum()/44.10))
print("% Nan Values BusinessTravel: "+ str(disp_df['BusinessTravel'].isna().sum()/44.10))
print("% Nan Values Department: "+ str(disp_df['Department'].isna().sum()/44.10))
print("% Nan Values DistanceFromHome: "+ str(disp_df['DistanceFromHome'].isna().sum()/44.10))
print("% Nan Values Education: "+ str(disp_df['Education'].isna().sum()/44.10))
print("% Nan Values EducationField: "+ str(disp_df['EducationField'].isna().sum()/44.10))
print("% Nan Values EmployeeCount: "+ str(disp_df['EmployeeCount'].isna().sum()/44.10))
print("% Nan Values EmployeeID: "+ str(disp_df['EmployeeID'].isna().sum()/44.10))
print("% Nan Values Gender: "+ str(disp_df['Gender'].isna().sum()/44.10))
print("% Nan Values JobLevel: "+ str(disp_df['JobLevel'].isna().sum()/44.10))
print("% Nan Values JobRole: "+ str(disp_df['JobRole'].isna().sum()/44.10))
print("% Nan Values MaritalStatus: "+ str(disp_df['MaritalStatus'].isna().sum()/44.10))
print("% Nan Values MonthlyIncome: "+ str(disp_df['MonthlyIncome'].isna().sum()/44.10))
print("% Nan Values NumCompaniesWorked: "+ str(disp_df['NumCompaniesWorked'].isna().sum()/44.10))
print("% Nan Values Over18: "+ str(disp_df['Over18'].isna().sum()/44.10))
print("% Nan Values PercentSalaryHike: "+ str(disp_df['PercentSalaryHike'].isna().sum()/44.10))
print("% Nan Values StandardHours: "+ str(disp_df['StandardHours'].isna().sum()/44.10))
print("% Nan Values StockOptionLevel: "+ str(disp_df['StockOptionLevel'].isna().sum()/44.10))
print("% Nan Values TotalWorkingYears: "+ str(disp_df['TotalWorkingYears'].isna().sum()/44.10))
print("% Nan Values TrainingTimesLastYear: "+ str(disp_df['TrainingTimesLastYear'].isna().sum()/44.10))
print("% Nan Values YearsAtCompany: "+ str(disp_df['YearsAtCompany'].isna().sum()/44.10))
print("% Nan Values YearsSinceLastPromotion: "+ str(disp_df['YearsSinceLastPromotion'].isna().sum()/44.10))
print("% Nan Values YearsWithCurrManager: "+ str(disp_df['YearsWithCurrManager'].isna().sum()/44.10))
print("--------------------------------------------------------------")
print("Total of NaN Values : "+ str(disp_df.isna().sum().sum()))

% Nan Values hrs: 18.934240362811792
% Nan Values absences: 18.095238095238095
% Nan Values JobInvolvement: 20.839002267573697
% Nan Values PerformanceRating: 17.732426303854876
% Nan Values EnvironmentSatisfaction: 16.621315192743765
% Nan Values JobSatisfaction: 16.39455782312925
% Nan Values WorkLifeBalance: 0.8616780045351473
% Nan Values Age: 21.723356009070294
% Nan Values Attrition: 0.0
% Nan Values BusinessTravel: 19.727891156462583
% Nan Values Department: 20.113378684807255
% Nan Values DistanceFromHome: 20.045351473922903
% Nan Values Education: 20.589569160997733
% Nan Values EducationField: 16.53061224489796
% Nan Values EmployeeCount: 20.839002267573697
% Nan Values EmployeeID: 0.0
% Nan Values Gender: 16.349206349206348
% Nan Values JobLevel: 0.0
% Nan Values JobRole: 15.963718820861677
% Nan Values MaritalStatus: 16.643990929705215
% Nan Values MonthlyIncome: 20.997732426303855
% Nan Values NumCompaniesWorked: 20.839002267573697
% Nan Values Over18: 17.86848072562358
% 

In [ ]:
def constant_value_features(df):
    return [e for e in df.columns if df[e].nunique() == 1]

constant_col = constant_value_features(disp_df)
print(constant_col)

['EmployeeCount', 'Over18', 'StandardHours']


In [ ]:
print(disp_df['EmployeeCount'].head(10))
print(disp_df['Over18'].head(10))
print(disp_df['StandardHours'].head(10))

1     1.0
6     1.0
13    1.0
28    1.0
30    1.0
35    1.0
38    NaN
59    1.0
65    1.0
69    1.0
Name: EmployeeCount, dtype: float64
1       Y
6       Y
13    NaN
28    NaN
30      Y
35      Y
38      Y
59      Y
65      Y
69    NaN
Name: Over18, dtype: object
1     8.0
6     8.0
13    8.0
28    8.0
30    8.0
35    NaN
38    8.0
59    8.0
65    8.0
69    8.0
Name: StandardHours, dtype: float64


In [ ]:
disp_df=disp_df.drop(columns=['EmployeeCount', 'Over18', 'StandardHours'])

In [ ]:
print(disp_df['Attrition'].unique())
print(disp_df['BusinessTravel'].unique())
print(disp_df['Department'].unique())
print(disp_df['EducationField'].unique())
print(disp_df['Gender'].unique())
print(disp_df['JobRole'].unique())
print(disp_df['MaritalStatus'].unique())

['Yes' 'No']
['Travel_Frequently' 'Travel_Rarely' 'Non-Travel' nan]
['Research & Development' nan 'Human Resources' 'Sales']
['Life Sciences' 'Medical' nan 'Human Resources' 'Marketing'
 'Technical Degree' 'Other']
['Female' 'Male' nan]
['Research Scientist' nan 'Manager' 'Sales Executive'
 'Laboratory Technician' 'Manufacturing Director'
 'Healthcare Representative' 'Research Director' 'Sales Representative'
 'Human Resources']
['Single' nan 'Divorced' 'Married']


In [ ]:
print("Clase Yes: " + str(disp_df[disp_df['Attrition'] == 'Yes']['Attrition'].count()))
print("Clase No: " + str(disp_df[disp_df['Attrition'] == 'No']['Attrition'].count()))

Clase Yes: 711
Clase No: 3699


Nos encontramos ante un problema de clasificación, puesto que el objetivo del conjunto de datos y del modelo a crear es predecir si un empleado puede abandonar la empresa o no, por lo que el modelo se encargará de clasificar a los distintos empleados en si pueden abandonar la empresa o no. La variable de salida es attrition, la cual tiene dos posibles valores, 'Yes' o 'No', por lo que estamos ante un problema de clasificación binaria. Como puede observarse, el problema es desbalanceado, encontrando que un 83,87% de las instancias pertenecen a la clase 'No' (attrition = 'No'), por lo que significa que un modelo trivial tendría un acierto del 83,87% si clasificara todos los datos como 'No'.

# **Train/Test Split**

---



In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

# Procesamiento de valores numéricos.
features_num = ["hrs", "absences", "JobInvolvement", "PerformanceRating", "EnvironmentSatisfaction", "JobSatisfaction", "WorkLifeBalance", "Age", "DistanceFromHome", "Education","EmployeeID", "JobLevel","MonthlyIncome", "NumCompaniesWorked", "PercentSalaryHike", "StockOptionLevel", "TotalWorkingYears", "TrainingTimesLastYear", "YearsAtCompany", "YearsSinceLastPromotion","YearsWithCurrManager"]
imputer_num = SimpleImputer(strategy='mean')
pipeline_num = Pipeline(
    steps=[
        ("imputer", imputer_num)
    ]
)

# Procesamiento de valores categóricos.
features_cat = ["BusinessTravel", "Department", "EducationField", "Gender", "JobRole", "MaritalStatus"]
imputer_cat = SimpleImputer(strategy='most_frequent')
pipeline_cat = Pipeline(
    steps=[
        ("imputer", imputer_cat)
    ]
)

# Pre-procesador "global".
# Dependiendo del tipo de columna se aplica una transformación u otra.

processor = ColumnTransformer(
    transformers=[
        ("num", pipeline_num, features_num),
        ("cat", pipeline_cat, features_cat),
    ]
)

# Realizamos la transformación.
disp_df_final = processor.fit_transform(disp_df.drop(columns='Attrition'))

In [ ]:
disp_df = pd.DataFrame(disp_df_final, columns=["hrs", "absences", "JobInvolvement", "PerformanceRating", "EnvironmentSatisfaction", "JobSatisfaction", "WorkLifeBalance", "Age", "DistanceFromHome", "Education","EmployeeID", "JobLevel","MonthlyIncome", "NumCompaniesWorked", "PercentSalaryHike", "StockOptionLevel", "TotalWorkingYears", "TrainingTimesLastYear", "YearsAtCompany", "YearsSinceLastPromotion","YearsWithCurrManager","BusinessTravel", "Department", "EducationField", "Gender", "JobRole", "MaritalStatus"])

print(disp_df)
print(type(disp_df))

            hrs   absences JobInvolvement PerformanceRating  \
0      7.315971       13.0            2.0               4.0   
1      6.450877       17.0            3.0               4.0   
2      8.871421       14.0            2.0               3.0   
3     10.713066        6.0            2.0               3.0   
4      9.662808       11.0            2.0               3.0   
...         ...        ...            ...               ...   
4405   8.316921        6.0            3.0               3.0   
4406   5.897197        8.0            2.0               3.0   
4407   7.149526       18.0            3.0               4.0   
4408   9.187612  12.762735            2.0               3.0   
4409    6.51179       17.0            4.0               3.0   

     EnvironmentSatisfaction JobSatisfaction WorkLifeBalance        Age  \
0                        3.0             2.0             4.0       31.0   
1                        1.0             3.0             1.0       28.0   
2                 

In [ ]:
df_temp1=pd.get_dummies(disp_df.Department)
df_temp2=pd.get_dummies(disp_df.EducationField)
df_temp3=pd.get_dummies(disp_df.Gender)
df_temp4=pd.get_dummies(disp_df.JobRole)
df_temp5=pd.get_dummies(disp_df.MaritalStatus)

disp_df=disp_df.drop(columns=['Department', 'EducationField', 'Gender','JobRole','MaritalStatus'])
df_ohe=[disp_df,df_temp1,df_temp2, df_temp3, df_temp4, df_temp5]

disp_df=pd.concat(df_ohe, axis=1)
disp_df

hrs   absences JobInvolvement PerformanceRating  \
0      7.315971       13.0            2.0               4.0   
1      6.450877       17.0            3.0               4.0   
2      8.871421       14.0            2.0               3.0   
3     10.713066        6.0            2.0               3.0   
4      9.662808       11.0            2.0               3.0   
...         ...        ...            ...               ...   
4405   8.316921        6.0            3.0               3.0   
4406   5.897197        8.0            2.0               3.0   
4407   7.149526       18.0            3.0               4.0   
4408   9.187612  12.762735            2.0               3.0   
4409    6.51179       17.0            4.0               3.0   

     EnvironmentSatisfaction JobSatisfaction WorkLifeBalance        Age  \
0                        3.0             2.0             4.0       31.0   
1                        1.0             3.0             1.0       28.0   
2                        1.0        2.736371             2.0       47.0   
3                        4.0             3.0             1.0       44.0   
4                        1.0        2.736371             3.0       26.0   
...                      ...             ...             ...        ...   
4405                     4.0             1.0             3.0       42.0   
4406                     4.0        2.736371             3.0       29.0   
4407                     1.0             3.0             3.0  37.081692   
4408                2.734838             1.0             3.0  37.081692   
4409                2.734838             3.0        2.761436       40.0   

     DistanceFromHome Education  ... Laboratory Technician Manager  \
0                10.0       1.0  ...                     0       0   
1                11.0       2.0  ...                     0       0   
2                 1.0       1.0  ...                     0       0   
3            9.221781       2.0  ...                     0       0   
4                 4.0       3.0  ...                     0       0   
...               ...       ...  ...                   ...     ...   
4405              5.0       4.0  ...                     0       0   
4406              2.0       4.0  ...                     0       0   
4407             25.0       2.0  ...                     0       0   
4408             18.0       2.0  ...                     1       0   
4409             28.0       3.0  ...                     1       0   

     Manufacturing Director Research Director Research Scientist  \
0                         0                 0                  1   
1                         0                 0                  0   
2                         0                 0                  1   
3                         0                 0                  1   
4                         0                 0                  1   
...                     ...               ...                ...   
4405                      0                 0                  1   
4406                      0                 0                  0   
4407                      0                 0                  0   
4408                      0                 0                  0   
4409                      0                 0                  0   

     Sales Executive Sales Representative Divorced Married Single  
0                  0                    0        0       0      1  
1                  1                    0        0       0      1  
2                  0                    0        0       1      0  
3                  0                    0        1       0      0  
4                  0                    0        1       0      0  
...              ...                  ...      ...     ...    ...  
4405               0                    0        0       0      1  
4406               1                    0        1       0      0  
4407               1                    0        0       1      0  
4408            

In [ ]:
df_temp6=disp_df.copy()

scale_mapper = {"Non-Travel":1, "Travel_Rarely":2, "Travel_Frequently":3}

df_temp6=df_temp6.drop(columns=["hrs", "absences", "JobInvolvement", "PerformanceRating", "EnvironmentSatisfaction", "JobSatisfaction", "WorkLifeBalance", "Age", "DistanceFromHome", "Education","EmployeeID", "JobLevel","MonthlyIncome", "NumCompaniesWorked", "PercentSalaryHike", "StockOptionLevel", "TotalWorkingYears", "TrainingTimesLastYear", "YearsAtCompany", "YearsSinceLastPromotion","YearsWithCurrManager"])

df_temp6["BusinessTravel"] = df_temp6["BusinessTravel"].replace(scale_mapper)

df_temp6=df_temp6.BusinessTravel
df_temp6

disp_df=disp_df.drop(columns=["BusinessTravel"])

df_final_array=[disp_df,df_temp6]

disp_df=pd.concat(df_final_array, axis=1)
disp_df


hrs   absences JobInvolvement PerformanceRating  \
0      7.315971       13.0            2.0               4.0   
1      6.450877       17.0            3.0               4.0   
2      8.871421       14.0            2.0               3.0   
3     10.713066        6.0            2.0               3.0   
4      9.662808       11.0            2.0               3.0   
...         ...        ...            ...               ...   
4405   8.316921        6.0            3.0               3.0   
4406   5.897197        8.0            2.0               3.0   
4407   7.149526       18.0            3.0               4.0   
4408   9.187612  12.762735            2.0               3.0   
4409    6.51179       17.0            4.0               3.0   

     EnvironmentSatisfaction JobSatisfaction WorkLifeBalance        Age  \
0                        3.0             2.0             4.0       31.0   
1                        1.0             3.0             1.0       28.0   
2                        1.0        2.736371             2.0       47.0   
3                        4.0             3.0             1.0       44.0   
4                        1.0        2.736371             3.0       26.0   
...                      ...             ...             ...        ...   
4405                     4.0             1.0             3.0       42.0   
4406                     4.0        2.736371             3.0       29.0   
4407                     1.0             3.0             3.0  37.081692   
4408                2.734838             1.0             3.0  37.081692   
4409                2.734838             3.0        2.761436       40.0   

     DistanceFromHome Education  ... Manager Manufacturing Director  \
0                10.0       1.0  ...       0                      0   
1                11.0       2.0  ...       0                      0   
2                 1.0       1.0  ...       0                      0   
3            9.221781       2.0  ...       0                      0   
4                 4.0       3.0  ...       0                      0   
...               ...       ...  ...     ...                    ...   
4405              5.0       4.0  ...       0                      0   
4406              2.0       4.0  ...       0                      0   
4407             25.0       2.0  ...       0                      0   
4408             18.0       2.0  ...       0                      0   
4409             28.0       3.0  ...       0                      0   

     Research Director Research Scientist Sales Executive  \
0                    0                  1               0   
1                    0                  0               1   
2                    0                  1               0   
3                    0                  1               0   
4                    0                  1               0   
...                ...                ...             ...   
4405                 0                  1               0   
4406                 0                  0               1   
4407                 0                  0               1   
4408                 0                  0               0   
4409                 0                  0               0   

     Sales Representative Divorced Married Single BusinessTravel  
0                       0        0       0      1              3  
1                       0        0       0      1              2  
2                       0        0       1      0              1  
3                       0        1       0      0              3  
4                       0        1       0      0              2  
...                   ...      ...     ...    ...            ...  
4405                    0        0       0      1              2  
4406                    0        1       0      0              2  
4407                    0        0       1      0              2  
4408                    0        0       1      0              2  
4409                    0      

In [ ]:
scale_mapper = {"No":0, "Yes":1}

disp_df_target = disp_df_target.replace(scale_mapper)

disp_df_target

1       1
6       1
13      1
28      1
30      1
       ..
4405    0
4406    0
4407    0
4408    0
4409    0
Name: Attrition, Length: 4410, dtype: int64

In [ ]:
data=disp_df.to_numpy()
target=disp_df_target.to_numpy()

print(data)
print(target)

print("Tamaños de los arrays: ")
print("Global: " + str(disp_df.shape))
print("Entradas: " + str(data.shape))
print("Salidas: " + str(target.shape))

[[7.315970548861944 13.0 2.0 ... 0 1 3]
 [6.450876840696111 17.0 3.0 ... 0 1 2]
 [8.8714212405175 14.0 2.0 ... 1 0 1]
 ...
 [7.149525881302778 18.0 3.0 ... 1 0 2]
 [9.187611557340277 12.762735326688816 2.0 ... 1 0 2]
 [6.511790495314444 17.0 4.0 ... 0 0 2]]
[1 1 1 ... 0 0 0]
Tamaños de los arrays: 
Global: (4410, 45)
Entradas: (4410, 45)
Salidas: (4410,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.33, random_state=42, stratify=target)

In [ ]:
unique_train, counts_train = np.unique(y_train, return_counts=True)
unique_test, counts_test = np.unique(y_test, return_counts=True)
print(dict(zip(unique_train, counts_train)))
print(dict(zip(unique_test, counts_test)))
print("Porcentaje de datos de la clase NO en:")
print("Train: " + str(counts_train[0]/y_train.shape[0]))
print("Test: " + str(counts_test[0]/y_test.shape[0]))
print("Porcentaje de datos de la clase YES en:")
print("Train: " + str(counts_train[1]/y_train.shape[0]))
print("Test: " + str(counts_test[1]/y_test.shape[0]))

{0: 2478, 1: 476}
{0: 1221, 1: 235}
Porcentaje de datos de la clase NO en:
Train: 0.8388625592417062
Test: 0.8385989010989011
Porcentaje de datos de la clase YES en:
Train: 0.16113744075829384
Test: 0.1614010989010989


# ***Modelo*** ***LogisticRegression***

---



In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, f1_score, confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

pipeline = make_pipeline(StandardScaler(), LogisticRegression(random_state=42, class_weight='balanced'))

clf = pipeline.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Balanced Accurancy Score: " + str(balanced_accuracy_score(y_test, y_pred)))
print("F1 Score: " + str(f1_score(y_test, y_pred, average='weighted')))
print("Matriz de confusión: ")
print(confusion_matrix(y_test, y_pred))

Balanced Accurancy Score: 0.732219840730479
F1 Score: 0.7709960158185011
Matriz de confusión: 
[[910 311]
 [ 66 169]]
