# **Carga de datos**

---



In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

# Cargar los datos
disp_df = pd.read_pickle("attrition_available_17.pkl")

In [ ]:
# Mostrar los datos y el nombre de las columnas
display(disp_df)

hrs  absences  JobInvolvement  PerformanceRating  \
1      7.315971      13.0             2.0                4.0   
6      6.450877      17.0             3.0                4.0   
13     8.871421      14.0             2.0                3.0   
28    10.713066       6.0             2.0                3.0   
30     9.662808      11.0             2.0                3.0   
...         ...       ...             ...                ...   
4405   8.316921       6.0             3.0                3.0   
4406   5.897197       8.0             2.0                3.0   
4407   7.149526      18.0             3.0                4.0   
4408   9.187612       NaN             2.0                3.0   
4409   6.511790      17.0             4.0                3.0   

      EnvironmentSatisfaction  JobSatisfaction  WorkLifeBalance   Age  \
1                         3.0              2.0              4.0  31.0   
6                         1.0              3.0              1.0  28.0   
13                        1.0              NaN              2.0  47.0   
28                        4.0              3.0              1.0  44.0   
30                        1.0              NaN              3.0  26.0   
...                       ...              ...              ...   ...   
4405                      4.0              1.0              3.0  42.0   
4406                      4.0              NaN              3.0  29.0   
4407                      1.0              3.0              3.0   NaN   
4408                      NaN              1.0              3.0   NaN   
4409                      NaN              3.0              NaN  40.0   

     Attrition     BusinessTravel  ... NumCompaniesWorked  Over18  \
1          Yes  Travel_Frequently  ...                0.0       Y   
6          Yes      Travel_Rarely  ...                NaN       Y   
13         Yes         Non-Travel  ...                1.0     NaN   
28         Yes  Travel_Frequently  ...                3.0     NaN   
30         Yes      Travel_Rarely  ...                2.0       Y   
...        ...                ...  ...                ...     ...   
4405        No      Travel_Rarely  ...                3.0       Y   
4406        No      Travel_Rarely  ...                2.0       Y   
4407        No      Travel_Rarely  ...                0.0       Y   
4408        No      Travel_Rarely  ...                NaN       Y   
4409        No      Travel_Rarely  ...                0.0       Y   

      PercentSalaryHike StandardHours  StockOptionLevel  TotalWorkingYears  \
1                  23.0           8.0               1.0                6.0   
6                   NaN           8.0               1.0                5.0   
13                 11.0           8.0               NaN                NaN   
28                 14.0           8.0               1.0               19.0   
30                 11.0           8.0               0.0                5.0   
...                 ...           ...               ...                ...   
4405               17.0           8.0               NaN               10.0   
4406               15.0           8.0               0.0                NaN   
4407               20.0           8.0               NaN                NaN   
4408               14.0           8.0               NaN                NaN   
4409               12.0           8.0               0.0                NaN   

     TrainingTimesLastYear  YearsAtCompany YearsSinceLastPromotion  \
1                      3.0             5.0                     1.0   
6                      2.0             0.0                     0.0   
13                     4.0            10.0                     9.0   
28                     2.0             1.0                     0.0   
30                     5.0             3.0                     0.0   
...                    ...             ...                     ...   
4405                   NaN             NaN                     NaN   
4406                   2.0             3

En el dataset proporcionado se encuentran 4410 instancias y 31 atributos, de los cuales hay 23 numéricos, 2 ordinales (MaritalStatus y BusinessTravel) y 6 categóricos.

# **Análisis Exploratorio de Datos (EDA)**

---

In [ ]:
# Primero, observamos el tipo de dato de cada columna para ver si hay alguna que contiene valores nulos
disp_df.dtypes

hrs                        float64
absences                   float64
JobInvolvement             float64
PerformanceRating          float64
EnvironmentSatisfaction    float64
JobSatisfaction            float64
WorkLifeBalance            float64
Age                        float64
Attrition                   object
BusinessTravel              object
Department                  object
DistanceFromHome           float64
Education                  float64
EducationField              object
EmployeeCount              float64
EmployeeID                   int64
Gender                      object
JobLevel                     int64
JobRole                     object
MaritalStatus               object
MonthlyIncome              float64
NumCompaniesWorked         float64
Over18                      object
PercentSalaryHike          float64
StandardHours              float64
StockOptionLevel           float64
TotalWorkingYears          float64
TrainingTimesLastYear      float64
YearsAtCompany      

In [ ]:
print("% Nan Values hrs: "+ str(disp_df['hrs'].isna().sum()/44.10))
print("% Nan Values absences: "+ str(disp_df['absences'].isna().sum()/44.10))
print("% Nan Values JobInvolvement: "+ str(disp_df['JobInvolvement'].isna().sum()/44.10))
print("% Nan Values PerformanceRating: "+ str(disp_df['PerformanceRating'].isna().sum()/44.10))
print("% Nan Values EnvironmentSatisfaction: "+ str(disp_df['EnvironmentSatisfaction'].isna().sum()/44.10))
print("% Nan Values JobSatisfaction: "+ str(disp_df['JobSatisfaction'].isna().sum()/44.10))
print("% Nan Values WorkLifeBalance: "+ str(disp_df['WorkLifeBalance'].isna().sum()/44.10))
print("% Nan Values Age: "+ str(disp_df['Age'].isna().sum()/44.10))
print("% Nan Values Attrition: "+ str(disp_df['Attrition'].isna().sum()/44.10))
print("% Nan Values BusinessTravel: "+ str(disp_df['BusinessTravel'].isna().sum()/44.10))
print("% Nan Values Department: "+ str(disp_df['Department'].isna().sum()/44.10))
print("% Nan Values DistanceFromHome: "+ str(disp_df['DistanceFromHome'].isna().sum()/44.10))
print("% Nan Values Education: "+ str(disp_df['Education'].isna().sum()/44.10))
print("% Nan Values EducationField: "+ str(disp_df['EducationField'].isna().sum()/44.10))
print("% Nan Values EmployeeCount: "+ str(disp_df['EmployeeCount'].isna().sum()/44.10))
print("% Nan Values EmployeeID: "+ str(disp_df['EmployeeID'].isna().sum()/44.10))
print("% Nan Values Gender: "+ str(disp_df['Gender'].isna().sum()/44.10))
print("% Nan Values JobLevel: "+ str(disp_df['JobLevel'].isna().sum()/44.10))
print("% Nan Values JobRole: "+ str(disp_df['JobRole'].isna().sum()/44.10))
print("% Nan Values MaritalStatus: "+ str(disp_df['MaritalStatus'].isna().sum()/44.10))
print("% Nan Values MonthlyIncome: "+ str(disp_df['MonthlyIncome'].isna().sum()/44.10))
print("% Nan Values NumCompaniesWorked: "+ str(disp_df['NumCompaniesWorked'].isna().sum()/44.10))
print("% Nan Values Over18: "+ str(disp_df['Over18'].isna().sum()/44.10))
print("% Nan Values PercentSalaryHike: "+ str(disp_df['PercentSalaryHike'].isna().sum()/44.10))
print("% Nan Values StandardHours: "+ str(disp_df['StandardHours'].isna().sum()/44.10))
print("% Nan Values StockOptionLevel: "+ str(disp_df['StockOptionLevel'].isna().sum()/44.10))
print("% Nan Values TotalWorkingYears: "+ str(disp_df['TotalWorkingYears'].isna().sum()/44.10))
print("% Nan Values TrainingTimesLastYear: "+ str(disp_df['TrainingTimesLastYear'].isna().sum()/44.10))
print("% Nan Values YearsAtCompany: "+ str(disp_df['YearsAtCompany'].isna().sum()/44.10))
print("% Nan Values YearsSinceLastPromotion: "+ str(disp_df['YearsSinceLastPromotion'].isna().sum()/44.10))
print("% Nan Values YearsWithCurrManager: "+ str(disp_df['YearsWithCurrManager'].isna().sum()/44.10))
print("--------------------------------------------------------------")
print("Total of NaN Values : "+ str(disp_df.isna().sum().sum()))

% Nan Values hrs: 18.934240362811792
% Nan Values absences: 18.095238095238095
% Nan Values JobInvolvement: 20.839002267573697
% Nan Values PerformanceRating: 17.732426303854876
% Nan Values EnvironmentSatisfaction: 16.621315192743765
% Nan Values JobSatisfaction: 16.39455782312925
% Nan Values WorkLifeBalance: 0.8616780045351473
% Nan Values Age: 21.723356009070294
% Nan Values Attrition: 0.0
% Nan Values BusinessTravel: 19.727891156462583
% Nan Values Department: 20.113378684807255
% Nan Values DistanceFromHome: 20.045351473922903
% Nan Values Education: 20.589569160997733
% Nan Values EducationField: 16.53061224489796
% Nan Values EmployeeCount: 20.839002267573697
% Nan Values EmployeeID: 0.0
% Nan Values Gender: 16.349206349206348
% Nan Values JobLevel: 0.0
% Nan Values JobRole: 15.963718820861677
% Nan Values MaritalStatus: 16.643990929705215
% Nan Values MonthlyIncome: 20.997732426303855
% Nan Values NumCompaniesWorked: 20.839002267573697
% Nan Values Over18: 17.86848072562358
% 

In [ ]:
disp_df = disp_df.fillna(disp_df.mean())
disp_df = disp_df.fillna(disp_df.mode())

<ipython-input-72-fc4ba61a5adc>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  disp_df = disp_df.fillna(disp_df.mean())


In [ ]:
print("% Nan Values hrs: "+ str(disp_df['hrs'].isna().sum()/44.10))
print("% Nan Values absences: "+ str(disp_df['absences'].isna().sum()/44.10))
print("% Nan Values JobInvolvement: "+ str(disp_df['JobInvolvement'].isna().sum()/44.10))
print("% Nan Values PerformanceRating: "+ str(disp_df['PerformanceRating'].isna().sum()/44.10))
print("% Nan Values EnvironmentSatisfaction: "+ str(disp_df['EnvironmentSatisfaction'].isna().sum()/44.10))
print("% Nan Values JobSatisfaction: "+ str(disp_df['JobSatisfaction'].isna().sum()/44.10))
print("% Nan Values WorkLifeBalance: "+ str(disp_df['WorkLifeBalance'].isna().sum()/44.10))
print("% Nan Values Age: "+ str(disp_df['Age'].isna().sum()/44.10))
print("% Nan Values Attrition: "+ str(disp_df['Attrition'].isna().sum()/44.10))
print("% Nan Values BusinessTravel: "+ str(disp_df['BusinessTravel'].isna().sum()/44.10))
print("% Nan Values Department: "+ str(disp_df['Department'].isna().sum()/44.10))
print("% Nan Values DistanceFromHome: "+ str(disp_df['DistanceFromHome'].isna().sum()/44.10))
print("% Nan Values Education: "+ str(disp_df['Education'].isna().sum()/44.10))
print("% Nan Values EducationField: "+ str(disp_df['EducationField'].isna().sum()/44.10))
print("% Nan Values EmployeeCount: "+ str(disp_df['EmployeeCount'].isna().sum()/44.10))
print("% Nan Values EmployeeID: "+ str(disp_df['EmployeeID'].isna().sum()/44.10))
print("% Nan Values Gender: "+ str(disp_df['Gender'].isna().sum()/44.10))
print("% Nan Values JobLevel: "+ str(disp_df['JobLevel'].isna().sum()/44.10))
print("% Nan Values JobRole: "+ str(disp_df['JobRole'].isna().sum()/44.10))
print("% Nan Values MaritalStatus: "+ str(disp_df['MaritalStatus'].isna().sum()/44.10))
print("% Nan Values MonthlyIncome: "+ str(disp_df['MonthlyIncome'].isna().sum()/44.10))
print("% Nan Values NumCompaniesWorked: "+ str(disp_df['NumCompaniesWorked'].isna().sum()/44.10))
print("% Nan Values Over18: "+ str(disp_df['Over18'].isna().sum()/44.10))
print("% Nan Values PercentSalaryHike: "+ str(disp_df['PercentSalaryHike'].isna().sum()/44.10))
print("% Nan Values StandardHours: "+ str(disp_df['StandardHours'].isna().sum()/44.10))
print("% Nan Values StockOptionLevel: "+ str(disp_df['StockOptionLevel'].isna().sum()/44.10))
print("% Nan Values TotalWorkingYears: "+ str(disp_df['TotalWorkingYears'].isna().sum()/44.10))
print("% Nan Values TrainingTimesLastYear: "+ str(disp_df['TrainingTimesLastYear'].isna().sum()/44.10))
print("% Nan Values YearsAtCompany: "+ str(disp_df['YearsAtCompany'].isna().sum()/44.10))
print("% Nan Values YearsSinceLastPromotion: "+ str(disp_df['YearsSinceLastPromotion'].isna().sum()/44.10))
print("% Nan Values YearsWithCurrManager: "+ str(disp_df['YearsWithCurrManager'].isna().sum()/44.10))
print("--------------------------------------------------------------")
print("Total of NaN Values : "+ str(disp_df.isna().sum().sum()))

% Nan Values hrs: 0.0
% Nan Values absences: 0.0
% Nan Values JobInvolvement: 0.0
% Nan Values PerformanceRating: 0.0
% Nan Values EnvironmentSatisfaction: 0.0
% Nan Values JobSatisfaction: 0.0
% Nan Values WorkLifeBalance: 0.0
% Nan Values Age: 0.0
% Nan Values Attrition: 0.0
% Nan Values BusinessTravel: 19.727891156462583
% Nan Values Department: 20.113378684807255
% Nan Values DistanceFromHome: 0.0
% Nan Values Education: 0.0
% Nan Values EducationField: 16.53061224489796
% Nan Values EmployeeCount: 0.0
% Nan Values EmployeeID: 0.0
% Nan Values Gender: 16.349206349206348
% Nan Values JobLevel: 0.0
% Nan Values JobRole: 15.941043083900226
% Nan Values MaritalStatus: 16.621315192743765
% Nan Values MonthlyIncome: 0.0
% Nan Values NumCompaniesWorked: 0.0
% Nan Values Over18: 17.86848072562358
% Nan Values PercentSalaryHike: 0.0
% Nan Values StandardHours: 0.0
% Nan Values StockOptionLevel: 0.0
% Nan Values TotalWorkingYears: 0.0
% Nan Values TrainingTimesLastYear: 0.0
% Nan Values Year

In [ ]:
def constant_value_features(df):
    return [e for e in df.columns if df[e].nunique() == 1]

constant_col = constant_value_features(disp_df)
print(constant_col)

['EmployeeCount', 'Over18', 'StandardHours']


In [ ]:
print(disp_df['EmployeeCount'].head(10))
print(disp_df['Over18'].head(10))
print(disp_df['StandardHours'].head(10))

1     1.0
6     1.0
13    1.0
28    1.0
30    1.0
35    1.0
38    NaN
59    1.0
65    1.0
69    1.0
Name: EmployeeCount, dtype: float64
1       Y
6       Y
13    NaN
28    NaN
30      Y
35      Y
38      Y
59      Y
65      Y
69    NaN
Name: Over18, dtype: object
1     8.0
6     8.0
13    8.0
28    8.0
30    8.0
35    NaN
38    8.0
59    8.0
65    8.0
69    8.0
Name: StandardHours, dtype: float64


In [ ]:
print("Clase Yes: " + str(disp_df[disp_df['Attrition'] == 'Yes']['Attrition'].count()))
print("Clase No: " + str(disp_df[disp_df['Attrition'] == 'No']['Attrition'].count()))

Clase Yes: 711
Clase No: 3699


Nos encontramos ante un problema de clasificación, puesto que el objetivo del conjunto de datos y del modelo a crear es predecir si un empleado puede abandonar la empresa o no, por lo que el modelo se encargará de clasificar a los distintos empleados en si pueden abandonar la empresa o no. La variable de salida es attrition, la cual tiene dos posibles valores, 'Yes' o 'No', por lo que estamos ante un problema de clasificación binaria. Como puede observarse, el problema es desbalanceado, encontrando que un 83,87% de las instancias pertenecen a la clase 'No' (attrition = 'No'), por lo que significa que un modelo trivial tendría un acierto del 83,87% si clasificara todos los datos como 'No'.

# **Train/Test Split**

---



In [ ]:
data=disp_df.copy().drop(columns=['Attrition']).to_numpy()
target=disp_df['Attrition'].to_numpy()

print(data)
print(target)

print("Tamaños de los arrays: ")
print("Global: " + str(disp_df.shape))
print("Entradas: " + str(data.shape))
print("Salidas: " + str(target.shape))

[[7.315970548861944 13.0 2.0 ... 5.0 1.0 4]
 [6.450876840696111 17.0 3.0 ... 0.0 0.0 0]
 [8.8714212405175 14.0 2.0 ... 10.0 9.0 9]
 ...
 [7.149525881302778 18.0 3.0 ... 4.0 1.0 2]
 [9.187611557340277 nan 2.0 ... nan 7.0 8]
 [6.511790495314444 17.0 4.0 ... 21.0 3.0 9]]
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
Tamaños de los arrays: 
Global: (4410, 31)
Entradas: (4410, 30)
Salidas: (4410,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.33, random_state=42)

In [ ]:
unique_train, counts_train = np.unique(y_train, return_counts=True)
unique_test, counts_test = np.unique(y_test, return_counts=True)
print(dict(zip(unique_train, counts_train)))
print(dict(zip(unique_test, counts_test)))
print("Porcentaje de datos de la clase NO en:")
print("Train: " + str(counts_train[0]/y_train.shape[0]))
print("Test: " + str(counts_test[0]/y_test.shape[0]))
print("Porcentaje de datos de la clase YES en:")
print("Train: " + str(counts_train[1]/y_train.shape[0]))
print("Test: " + str(counts_test[1]/y_test.shape[0]))

{'No': 2488, 'Yes': 466}
{'No': 1211, 'Yes': 245}
Porcentaje de datos de la clase NO en:
Train: 0.8422477995937712
Test: 0.8317307692307693
Porcentaje de datos de la clase YES en:
Train: 0.15775220040622884
Test: 0.16826923076923078
